### ISSUE TITLE
最新版Ghost安装失败

### ISSUE THREAD

**Issue by 3zeroed** [Archeb/Candy2#2]
#### This theme is invalid and cannot be activated. Fix the following errors and re-upload the theme.

**Fatal Errors**
Must-fix to activate theme

**Fatal Error:** A template file called index.hbs must be present
Your theme must have a template file called index.hbs.
Read [here](https://ghost.org/docs/api/handlebars-themes/context/) more about the required template structure and index.hbs in [particular](https://ghost.org/docs/api/handlebars-themes/context/index/).

Affected files: index.hbs
**Fatal Error:** A template file called post.hbs must be present
Your theme must have a template file called index.hbs.
Read [here](https://ghost.org/docs/api/handlebars-themes/context/) more about the required template structure and post.hbs in [particular](https://ghost.org/docs/api/handlebars-themes/context/index/).

Affected files: post.hbs

**Comment by Archeb** [comment]
这个不是直接安装到 Ghost 里的，是调用 Ghost API，主题需要有代码基础才能用，你可以看一下源码就知道了。
